### ISSUE TITLE
Question: Use X-Forwarded-For instead of the client IP

### ISSUE THREAD

**Issue by sowinski** [mholt/caddy-ratelimit#81]
Hi,

I’ve placed CloudFront in front of Caddy.

Currently, the client IP is the CloudFront IP, which I don’t want to use for rate limiting. Instead, I’d like to use the X-Forwarded-For header.

Is it possible to configure this? If so, how would you set it up?

Thank you!

**Comment by mholt** [comment]
What is your config that's not working?

Also see https://caddyserver.com/docs/json/apps/http/servers/trusted_proxies/

**Comment by sowinski** [comment]
Hi,

I currently have the following configuration for my Caddy web server:
```
caddy.log:
      caddy.reverse_proxy: "{{upstreams 8000}}"
      caddy.rate_limit.distributed:
      caddy.rate_limit.zone: "dynamic_global"
      caddy.rate_limit.zone.key: "{remote_host}"
      caddy.rate_limit.zone.window: "60s"
      caddy.rate_limit.zone.events: "180"
      caddy.handle_errors: 429
      caddy.handle_errors.respond: "\"Too Many Requests. Please try again later.\""
```
However, I want to place CloudFront in front of the Caddy web server. Since CloudFront forwards requests, the request IP will now be CloudFront's IP for every request. I assume this will cause issues with rate limiting.

I have two main concerns:

1. How can I properly test if the rate limiter is still working as expected?
2. How should I modify my Caddy settings to ensure the correct client IP is used instead of CloudFront’s IP?

Additionally, I noticed that Caddy's logs do not contain any information about which IP was rate-limited. Is there a way to configure Caddy to log more details, such as why a specific IP was blocked? Currently, I only see the 429 response, which looks like a normal request.
